# Generated by Django 5.2.7 on 2026-06-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('partial', 'Partial'), ('paymera', 'Paymera'), ('stripe', 'Stripe')], max_length=20),
        ),
    ]
