# Generated by Django 5.2.7 on 2026-06-22 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_pendingordercheckout'),
        ('vehicles', '0005_remove_vehicle_capacity_cubic_meters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingordercheckout',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingordercheckout',
            name='reserved_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_driver_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingordercheckout',
            name='reserved_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_checkouts', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='pendingordercheckout',
            name='reserved_workers',
            field=models.ManyToManyField(blank=True, related_name='pending_worker_checkouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
