# Generated by Django 5.2.7 on 2025-12-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='verified',
        ),
    ]
