# Generated by Django 5.2.7 on 2025-12-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_office_driverprofile_office_workerprofile_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_info',
        ),
    ]
