# Generated by Django 5.2.7 on 2026-01-08 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_driverprofile_vehicle_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_area', models.CharField(max_length=120)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20)),
                ('driver_license_number', models.CharField(max_length=100)),
                ('driver_license_photo', models.ImageField(upload_to='applications/driver/licenses/')),
                ('personal_photo', models.ImageField(upload_to='applications/driver/personal/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('interview_status', models.CharField(choices=[('pending_scheduling', 'Pending Scheduling'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending_scheduling', max_length=30)),
                ('interview_datetime', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(default='MoveLine Office', max_length=255)),
                ('suggested_interview_window', models.CharField(blank=True, max_length=255)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_area', models.CharField(max_length=120)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('can_lift_heavy', models.BooleanField(default=False)),
                ('personal_photo', models.ImageField(upload_to='applications/worker/personal/')),
                ('id_card_photo_front', models.ImageField(upload_to='applications/worker/id_cards/')),
                ('id_card_photo_back', models.ImageField(upload_to='applications/worker/id_cards/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('interview_status', models.CharField(choices=[('pending_scheduling', 'Pending Scheduling'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending_scheduling', max_length=30)),
                ('interview_datetime', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(default='MoveLine Office', max_length=255)),
                ('suggested_interview_window', models.CharField(blank=True, max_length=255)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
