# Generated by Django 5.2.7 on 2026-01-25 10:34

from django.db import migrations, models


def round_user_coords(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE users_driverprofile SET current_latitude = ROUND(current_latitude, 6) "
            "WHERE current_latitude IS NOT NULL"
        )
        cursor.execute(
            "UPDATE users_driverprofile SET current_longitude = ROUND(current_longitude, 6) "
            "WHERE current_longitude IS NOT NULL"
        )
        cursor.execute(
            "UPDATE users_workerprofile SET current_latitude = ROUND(current_latitude, 6) "
            "WHERE current_latitude IS NOT NULL"
        )
        cursor.execute(
            "UPDATE users_workerprofile SET current_longitude = ROUND(current_longitude, 6) "
            "WHERE current_longitude IS NOT NULL"
        )
        cursor.execute(
            "UPDATE users_office SET latitude = ROUND(latitude, 6) WHERE latitude IS NOT NULL"
        )
        cursor.execute(
            "UPDATE users_office SET longitude = ROUND(longitude, 6) WHERE longitude IS NOT NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_driverprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(round_user_coords, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='driverprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
