# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
