# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_workerprofile_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="suspended_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="suspended_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
