worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 25M;

    upstream moveline_asgi {
        server 127.0.0.1:8000;
    }

    server {
        listen 8088;
        server_name localhost 127.0.0.1;

        access_log C:/Users/R0DIUS/Desktop/Projects/Junior_Project/moveLine/deploy/nginx/logs/moveline_access.log;
        error_log C:/Users/R0DIUS/Desktop/Projects/Junior_Project/moveLine/deploy/nginx/logs/moveline_error.log;

        location /static/ {
            alias C:/Users/R0DIUS/Desktop/Projects/Junior_Project/moveLine/staticfiles/;
            expires 30d;
            add_header Cache-Control "public";
        }

        location /media/ {
            alias C:/Users/R0DIUS/Desktop/Projects/Junior_Project/moveLine/media/;
            expires 7d;
            add_header Cache-Control "public";
        }

        location / {
            proxy_pass http://moveline_asgi;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 300;
            proxy_send_timeout 300;
        }
    }
}
