# Generated by Django 5.2.7 on 2025-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analyze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='estimated_volume_cubic_m',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image_reference',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='suggested_vehicle_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
    ]
