# Generated by Codex on 2026-06-11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="driver",
            new_name="rated_user",
        ),
        migrations.AlterField(
            model_name="rating",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rated_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="target_role",
            field=models.CharField(
                choices=[("driver", "Driver"), ("worker", "Worker")],
                default="driver",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("order", "rated_user"),
                name="unique_rating_per_order_target",
            ),
        ),
    ]
