# Generated by Codex on 2026-06-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_rating_targets_driver_and_workers"),
        ("users", "0018_workerprofile_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_role", models.CharField(choices=[("driver", "Driver"), ("worker", "Worker")], max_length=20)),
                ("level", models.CharField(choices=[("notice", "Notice"), ("warning", "Warning"), ("suspension", "Suspension")], max_length=20)),
                ("reason", models.CharField(max_length=255)),
                ("average_rating", models.FloatField(default=0.0)),
                ("low_rating_count", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved")], default="open", max_length=20)),
                ("suspended_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="performance_alerts", to="users.user")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
