# Generated by Django 5.2.7 on 2025-12-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_reported_at',
        ),
    ]
