# Generated by Django 5.2.7 on 2025-12-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_cubic_meters',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
    ]
