# Generated by Django 5.2.7 on 2025-12-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_assignment_mode'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='id',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tracking', serialize=False, to='orders.order'),
        ),
    ]
