# Generated by Codex on 2026-06-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_assembly_order_disassembly"),
        ("tracking", "0002_remove_tracking_id_alter_tracking_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking",
            name="last_movement_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracking",
            name="stopped_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TrackingAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_type", models.CharField(choices=[("unexpected_stop", "Unexpected Stop")], default="unexpected_stop", max_length=30)),
                ("status", models.CharField(choices=[("open", "Open"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved")], default="open", max_length=20)),
                ("driver_reason", models.CharField(blank=True, choices=[("traffic", "Traffic"), ("vehicle_issue", "Vehicle Issue"), ("rest", "Rest"), ("extra_loading", "Extra Loading"), ("other", "Other")], max_length=30)),
                ("driver_note", models.TextField(blank=True)),
                ("driver_notified_at", models.DateTimeField(blank=True, null=True)),
                ("driver_responded_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notified_at", models.DateTimeField(blank=True, null=True)),
                ("customer_notified_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("driver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tracking_alerts", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tracking_alerts", to="orders.order")),
                ("tracking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="tracking.tracking")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
