# Generated by Django 5.2.7 on 2025-12-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_assignment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_workers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
