# Generated by Django 5.2.7 on 2025-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_required_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_vehicle_type',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20, null=True),
        ),
    ]
