# Generated by Django 5.2.7 on 2026-01-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='disassembly',
            field=models.BooleanField(default=False),
        ),
    ]
