# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_assembly_order_disassembly"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dropoff_floor",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="dropoff_has_elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_floor",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_has_elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="service_notes",
            field=models.TextField(blank=True),
        ),
    ]
