# Generated by Django 5.2.7 on 2026-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_property_floor_elevator_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('moving', 'Moving'), ('cleaning', 'Cleaning'), ('scrap', 'Scrap Removal')], default='moving', max_length=20),
        ),
    ]
